### ISSUE TITLE
How to correctly read 'novalue'/missing value in a .mf4 file

### ISSUE THREAD

**Issue by Eddiechiu** [ratal/mdfreader#129]
Hello Ratal,

Thank you very much for the mdfreader =D

I have a problem in parsing a .mf4 file.

In a channel of a .mf4 file, which means the speed time series of a car, there exists some points that only contain the time value and the speed value is missing. When I open this .mf4 file by TurboLab (a software that can parse .mf4 file), the speed value of these points is shown as 'novalue'. 

But when open this file by mdfreader, the missing speed value becomes some random value(sometimes zero, sometimes some other values that are not relevant). I don't know how to setup mdfreader to correctly read the 'novalue'. I think these 'novalue' should be read as 'None', maybe.

Thank you very much and hope you can help me~
Have a nice day ~

**Comment by ratal** [comment]
Hi,
Could you open your file with MDFValidator from Vector and check your channel ? It could be using a exotic way of storing your data (what is measurement tool ?) --> please make few snapshots of the channel group, channel block and conversion block description.
Otherwise and if not confidential, you could send this file and I will investigate.
Aymeric

**Comment by Eddiechiu** [comment]
<img width="645" alt="true" src="https://user-images.githubusercontent.com/16081098/35367332-c452f202-01b8-11e8-99f4-f475f00970df.PNG">
This is the right data. I open it by Turbolab (a software that can open mdf file), there are some missing values, but it just neglects them.

<img width="585" alt="withoutliers" src="https://user-images.githubusercontent.com/16081098/35367338-c7a17758-01b8-11e8-828d-f668ae4729b2.PNG">
This is the data with many outliers, open through 'mdfreader'. The outliers just appear where the data is missing. I don't know how to remove the outliers. I know a little about the so-called 'invalidation bit', maybe mdfreader didn't recognize the invalidation bit of the invalid data.
How can I find the channel block?
Thank you so much~

**Comment by ratal** [comment]
Hi,
mdfreader reads the invalid bits, no choise when reading complete data block. However, it does not yet handle them, so it exists during reading process but it is not part of final output.
I will implement it in masked arrays. I twill probably have several implications and might a bit of time.
In the mean time you can confirm if there are indeed invalid bits for this channel by looking at this channel group block cg_invalid_bytes in MDFValidator from Vector. If it is not null, there are invalid bits.

**Comment by Eddiechiu** [comment]
Thank you ~ and wish everything goes well !

**Comment by ratal** [comment]
Hi,
I made a first method prototype apply_invalid_bit() in last commit, you can have a try.

**Comment by Eddiechiu** [comment]
should I just use:
pip install --upgrade mdfreader

**Comment by Eddiechiu** [comment]
it still, cannot figure out the invaliad data. 

I'm not sure whether I download the lastest code.
I tried:
pip install --upgrade mdfreader

Also, I tried download the .zip and run:
python setup.py install

**Comment by ratal** [comment]
This is in github, not yet in pip as still under development, not released. To try you can do:
`git clone https://github.com/ratal/mdfreader.git`
then in the directory mdfreader
`python setup.py develop` or install

**Comment by danielhrisca** [comment]
To install from git:

``pip install -I https://github.com/ratal/mdfreader/archive/master.zip``  to ignore the already installed package 
or
``pip install -U https://github.com/ratal/mdfreader/archive/master.zip``  to upgrade the already installed package

**Comment by ratal** [comment]
Thanks Daniel, better

**Comment by cristi-neagu** [comment]
This brings up a point i've had on my mind for a while now. Not sure if this is the correct place to discuss this, but it is related.

Aymeric, would you consider having a multi-branch structure to the repository? With a main branch holding the released version, and a development branch holding any "beta" versions not yet released, with new feature branches stemming off this development branch? That way, we could have the git cloned repository straight in the sitepackages folder, and switch branches as necessary. It would also make development easier, since one could change the installed library directly, test it, and make a pull request without installing and uninstalling versions.

If there's a better way to manage this, let me know.

**Comment by ratal** [comment]
Yes, you are right, I am not using github in collaborative way, I could notice it.
I will create already a development branch and others according to the needs

**Comment by cristi-neagu** [comment]
You could possibly use this as a guide (but maybe not to its full complexity): http://nvie.com/posts/a-successful-git-branching-model/ Also, it can be a big change to your workflow, so make sure it is the correct thing to do.

**Comment by ratal** [comment]
I started to use more git branches.
Regardingh the original issue, as there are 2 months without feedback, I consider this is fixed.
Do not hesitate to repoen if not.
