### ISSUE TITLE
Concatenate Measurement Files?

### ISSUE THREAD

**Issue by wangdino** [ratal/mdfreader#25]
Hi ratal,

First of all thank you for the great work! 

I'm struggling to concatenate multiple MDF files (all of them are measured with same configuration hence sample rates, etc.). Do you know a way to do so?

Thanks!

**Comment by ratal** [comment]
Dear Wangdino,
There is already code existing for that. In mdfreader.py, there is a method of mdf class called mergeMdf. It is merging 2 mdf objects.
You can have a look at documentation for more details and you can also have a look at mdfconverter/mdfconverterui on_Convert_clicked() on how to use it.
Otherwise, you could also convert it into pandas and I am sure there are easy functions to do the same.
If it is ponctual need and you do not need python scriptign, you can use mdfconverter Qt graphical interface.

**Comment by ratal** [comment]
no feed back, I assume it solved your issue, closed
