### ISSUE TITLE
Error reading MDF4 using cn_composition

### ISSUE THREAD

**Issue by johp1029** [ratal/mdfreader#39]
Hello Ratal,

there seems to be an issue reading MDF4 files that are using cn_composition.
If I try to read a file I get the following Stacktrace:

`...
C:\Program Files\Anaconda3\lib\site-packages\mdfreader\mdfinfo4.py in readCNBlock(self, fid, dg, cg, channelNameList)
   1351                     if fid.read(4) in ('##CA', b'##CA'):
   1352                         self['CNBlock'][dg][cg][cn]['CABlock'] = CABlock(fid, self['CNBlock'][dg][cg][cn]['cn_composition'])
-> 1353                     elif self.mdfblockreadCHAR(fid, 4) in ('##CN', b'##CN'):
   1354                         self['CNBlock'][dg][cg][cn]['CNBlock'] = CNBlock(fid, self['CNBlock'][dg][cg][cn]['cn_composition'])
   1355                     else:

AttributeError: 'info4' object has no attribute 'mdfblockreadCHAR'`

This method is not available in info4 class as it does not inherit from MDFBlock.

Regards,
Johannes

**Comment by ratal** [comment]
Indeed, channel composition channel arrays even worse nested arrays are a work in progress.
You can try this:
`fid.seek(self['CNBlock'][dg][cg][cn]['cn_composition'])
                    id = fid.read(4)
                    if id in ('##CA', b'##CA'):
                        self['CNBlock'][dg][cg][cn]['CABlock'] = CABlock(fid, self['CNBlock'][dg][cg][cn]['cn_composition'])
                    elif id in ('##CN', b'##CN'):
                        self['CNBlock'][dg][cg][cn]['CNBlock'] = CNBlock(fid, self['CNBlock'][dg][cg][cn]['cn_composition'])`

**Comment by johp1029** [comment]
Hi,

I tested your suggested changes. The "AttributeError" is fixed now.

But now I am running into another error:

```
C:\Program Files\Anaconda3\lib\site-packages\mdfreader\mdf.py in __init__(self, fileName, channelList, convertAfterRead, filterChannelNames)
    106         self.fileName = fileName
    107         if fileName is not None:
--> 108             self.read(fileName, channelList=channelList, convertAfterRead=convertAfterRead, filterChannelNames=filterChannelNames)
    109 
    110 

C:\Program Files\Anaconda3\lib\site-packages\mdfreader\mdfreader.py in read(self, fileName, multiProc, channelList, convertAfterRead, filterChannelNames)
    363             self.read3(self.fileName, info, multiProc, channelList, convertAfterRead, filterChannelNames=False)
    364         else:  # MDF version 4.x. Channel by channel reading implemented
--> 365             self.read4(self.fileName, info, multiProc, channelList, convertAfterRead, filterChannelNames=False)
    366 
    367     def write(self, fileName=None):

C:\Program Files\Anaconda3\lib\site-packages\mdfreader\mdf4reader.py in read4(self, fileName, info, multiProc, channelList, convertAfterRead, filterChannelNames)
   1364                 for channelGroup in info['CGBlock'][dataGroup].keys():
   1365                     temp = record(dataGroup, channelGroup)  # create record class
-> 1366                     temp.loadInfo(info)  # load all info related to record
   1367                     buf.addRecord(temp)  # adds record to DATA
   1368                     recordID = info['CGBlock'][dataGroup][channelGroup]['cg_record_id']

C:\Program Files\Anaconda3\lib\site-packages\mdfreader\mdf4reader.py in loadInfo(self, info)
   1050                             embedded_bytes = True
   1051                             if self.recordToChannelMatching: # not first channel
-> 1052                                 self.recordToChannelMatching[Channel.name] = self.recordToChannelMatching[self[-2].name]
   1053                             else: # first channel
   1054                                 self.recordToChannelMatching[Channel.name] = Channel.name

KeyError: 'ANALOG_Frame.BusChannel'
```

Seems like line 1052 has to be changed to:
`self.recordToChannelMatching[Channel.name] = self[-2].name`

Am I correct?

**Comment by ratal** [comment]
First, do you use latest version ? ( I recently made improvements for composition)
Unfortunately, your proposal might avoid error for your file but I do not think this is correct, making error for other kind of files. After studying the code deeper, self.recordToChannelMatching[self[-2].name] should be correct --> The bug is coming from somewhere else I cannot identify so far.
To support you with this bug:
1. you could share the file
2. send the description of the files from mdfvalidator
3. try to understand what is wrong by yourself... with some guidance of course: This part of the code is dedicated to deal with channels that are embedded in a byte, length of several bits only. Reading bit by bits in the file is possible, activated by channel list input (using cython) but takes long time. By default, the code will read bytes by bytes with optimised numpy fromstring. It will read a byte channel (output a recarray given name the first bit channel contained). The attribute recordToChannelMatching describes the different bit channel names contained in the byte channel to be able to extract after datablock reading. Do not hesitate if you have other questions.
Up to you now
Aymeric

**Comment by ratal** [comment]
No news since 2 months, I guess latest commit solved your issue.
