### ISSUE TITLE
Improvement?: Use Lazy Initialization for MDFBlocks

### ISSUE THREAD

**Issue by mattispasch** [ratal/mdfreader#54]
In order to further improve performance on mdf-files with a large header (large number of channels), you could consider using lazy initialization for some mdfblocks (which are not always read anyway).

In my case, runtime was about halved, when using lazy init for:

- CommentBlock
- CCBlock
- CABlock
- ATBlock

I didn't file a pull request for this issue, as I don't know if this has negative effects in some cases.
I setup a branch to show my implementation: [https://github.com/mattispasch/mdfreader/tree/lazy_init_blocks](https://github.com/mattispasch/mdfreader/tree/lazy_init_blocks)

EDIT: My Implementation is not thread-safe!

**Comment by ratal** [comment]
I did several trials as you proposed but it had so many side effects (missing data, not thread safe as you mentionned because of unattended disk access) that I think it is dangerous for a benefit I could not grap.
Sorry, I will give up on this one but if you can show there is benefit I could persevere.
